services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: hw_02
      POSTGRES_USER: zhenyadatsenko
      POSTGRES_PASSWORD: 124455
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    restart: always

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql+psycopg2://zhenyadatsenko:124455@postgres:5432/hw_02
    volumes:
      - .:/app
    networks:
      - app_network
    restart: always

networks:
  app_network:

volumes:
  postgres_data:
